### ISSUE TITLE
Decode values to labels in read/view mode

### ISSUE THREAD

**Issue by softwareloop** [douglascrp/alfresco-value-assistance#1]
In read/view mode values are displayed:
![untitled](https://cloud.githubusercontent.com/assets/6525590/6130854/69f83cea-b148-11e4-8528-7a35b1a2db11.png)

while in edit mode, labels are displayed:
![untitled2](https://cloud.githubusercontent.com/assets/6525590/6130862/75679300-b148-11e4-8773-bcb935e70c0d.png)

**Comment by douglascrp** [comment]
@softwareloop I think it's fixed.
Can you grab the code and test it again?

Let me know the results.

**Comment by softwareloop** [comment]
Ok it works perfectly for me now.

**Comment by douglascrp** [comment]
OK. So I'm closing it.
Thank you
