### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by sulymankorj** [douglascrp/alfresco-value-assistance#2]
Dear,

I try to install this model but not working can you explain me how I can install it or can you give me amp files.

Thank you so much for your help

**Comment by douglascrp** [comment]
You have to download the source code.
Go to each of the project's module folders (alfresco-value-assistance-repo and alfresco-value-assistance-share) and run:
    mvn clean package
Amp files will be placed into target folder.
Let me know if you need more help.

**Comment by sulymankorj** [comment]
Thank you for your help but I got the below error:

[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.tsgrp:alfresco-value-assistance-repo:1.0-SNAPSHOT (/root/alfresco-value-assistance-repo/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.alfresco.maven:alfresco-sdk-parent:pom:1.2.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 12, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by sulymankorj** [comment]
I would inform you I try to make amp file in alfresco 5.0.c

**Comment by sulymankorj** [comment]
Please can you help me it is still not working. I can't convert it to amp

**Comment by douglascrp** [comment]
@sulymankorj Sorry for my late response...
So, in order to package it, you have to follow the steps described on this post http://ohej.dk/2014/10/alfresco-4-2-x-and-alfresco-sdk/
It's all about editing your ~/.m2/settings.xml file and include Sonatype's repository.
'<profiles>
<profile>
<id>allow-snapshots</id>
<activation><activeByDefault>true</activeByDefault></activation>
<repositories>
<repository>
<id>snapshots-repo</id>
<url>https://oss.sonatype.org/content/repositories/snapshots</url>
<releases><enabled>false</enabled></releases>
<snapshots><enabled>true</enabled></snapshots>
</repository>
</repositories>
</profile>
</profiles>'

**Comment by sulymankorj** [comment]
I am very sorry Still not success can you give me what I can do step by step I already add ~/.m2/settings.xml and I put the below code inside it 
<profiles>
<profile>
<id>allow-snapshots</id>
<activation><activeByDefault>true</activeByDefault></activation>
<repositories>
<repository>
<id>snapshots-repo</id>
<url>https://oss.sonatype.org/content/repositories/snapshots</url>
<releases><enabled>false</enabled></releases>
<snapshots><enabled>true</enabled></snapshots>
</repository>
</repositories>
</profile>
</profiles>

but still I facing error:

root@Amana:~/alfresco-value-assistance-master/alfresco-value-assistance-repo# mvn packege
[WARNING]
[WARNING] Some problems were encountered while building the effective settings
[WARNING] Expected root element 'settings' but found 'profiles' (position: START_TAG seen <profiles>... @1:10)  @ /root/.m2/settings.xml, line 1, column 10
[WARNING]
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.tsgrp:alfresco-value-assistance-repo:1.0-SNAPSHOT (/root/alfresco-value-assistance-master/alfresco-value-assistance-repo/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.alfresco.maven:alfresco-sdk-parent:pom:1.2.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 12, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by sulymankorj** [comment]
Please you can't create amp file for your extension.

**Comment by douglascrp** [comment]
Give me your email address and I can send those amps to you.

You have to read the error logs... you are not able to build it because you configured maven the wrong way.
The message says: [WARNING] Expected root element 'settings' but found 'profiles' (position: START_TAG seen ... @1:10) @ /root/.m2/settings.xml, line 1, column 10
That means your settings.xml file is wrong... you have to create a Maven valid xml configuration:

There are more elements you have to include on you file.
As a reference, this is mine:

```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          http://maven.apache.org/xsd/settings-1.0.0.xsd">
        <localRepository/>
        <interactiveMode/>
        <usePluginRegistry/>
        <offline/>
        <pluginGroups/>
        <servers/>
        <mirrors/>
        <proxies/>
        <profiles>
                <profile>
                        <id>allow-snapshots</id>
                        <activation><activeByDefault>true</activeByDefault></activation>
                        <repositories>
                                <repository>
                                        <id>snapshots-repo</id>
                                        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                                        <releases><enabled>false</enabled></releases>
                                        <snapshots><enabled>true</enabled></snapshots>
                                </repository>
                        </repositories>
                </profile>
        </profiles>
        <activeProfiles/>
</settings>```

Yours is missing settings tag.
Try to configure yours like mine an try again, please.

**Comment by sulymankorj** [comment]
sulymankorj@yahoo.com

many thank you

**Comment by douglascrp** [comment]
@sulymankorj I've just changed the project's readme file to include all the instructions I gave to you.
Please, take a look.

I'm closing this issue.

**Comment by sulymankorj** [comment]
Thank you so much sorry but this is the first time I try to create amp file

**Comment by sulymankorj** [comment]
I should fill all the data as 
        <servers/>
        <mirrors/>
        <proxies/>

or I can keep it by default

**Comment by huarte** [comment]
Hi douglas, do you conserve the AMP file for @sulymankorj ?   Can you send me a copy of that?  
huarte94     @     gmail.com

Thank you!

**Comment by douglascrp** [comment]
@huarte Files sent to your email.

Sorry for the late response.

**Comment by huarte** [comment]
Thanks,

The AMP, worked fine!



2016-01-21 14:07 GMT+01:00 Douglas C. R. Paes <notifications@github.com>:
