### ISSUE TITLE
Empty dropdowns

### ISSUE THREAD

**Issue by anghelutar** [douglascrp/alfresco-value-assistance#5]
Hello,

I am testing this on an enterprise Alfresco 5.0, but I can't make it work.

To test with the out-of-the-box example, I added the "level" control parameter to share-config-custom, for properties dm:color and dm:department:

```xml
 <control template="/form-controls/dynamic-dropdown.ftl">
                                                        <control-param name="picklistName">Color</control-param>
                                                        <control-param name="level">1</control-param>
                                                </control>
</pre>
```
However, when editing properties to a document with aspect dm:demo applied, I get empty drop-downs for Color and Department. When checking network calls executed, I see there are 404 for 
http://localhost:8081/share/res/js/dependent-control.js and
http://localhost:8081/share/res/js/dynamic-dropdown.js

How can I fix this? Any help is warmy appreciated.

Thank you very much,
roxana

**Comment by douglascrp** [comment]
The project is composed of two amp files, one for alfresco, and other for share.
You have to install both of them.

Try it and let me know the result.
If it works, please, close the issue.

**Comment by anghelutar** [comment]
Both amps are installed:

```bash
✔ /opt/alfresco-5.0.1/tomcat/webapps/share 
20:26 $ ls -ltr js/dynamic-dropdown*
-rw-rw-r-- 1 rox rox 2876 Mai  7 22:59 js/dynamic-dropdown-min.js
-rw-rw-r-- 1 rox rox 6463 Mai  7 22:59 js/dynamic-dropdown.js
✔ /opt/alfresco-5.0.1/tomcat/webapps/share 
```
Still, the errors are there.

roxana

**Comment by anghelutar** [comment]
Hello again,

It seems it collides with another module installed on the system: if I install it on a vanilla Alfresco (tried 5.1 this time, after recompiling), works fine. 
Thanks a lot for the prompt reply and count one more happy user of the module!

I will close the issue.

roxana

**Comment by douglascrp** [comment]
@anghelutar Perfect.
Thank you for the feedback.
